-- phpMyAdmin SQL Dump
-- version 4.7.9
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: 27-Ago-2018 às 12:56
-- Versão do servidor: 5.7.21
-- PHP Version: 7.1.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `comicsnews`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `noticia`
--

CREATE TABLE `noticia` (
  `ID` int(11) NOT NULL,
  `titulo` varchar(100) NOT NULL,
  `descricao` text NOT NULL,
  `img` varchar(100) NOT NULL,
  `data` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `autor` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Extraindo dados da tabela `noticia`
--

INSERT INTO `noticia` (`ID`, `titulo`, `descricao`, `img`, `data`, `autor`) VALUES
(57, 'Mob Psycho 100 irá virar quadrinho!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ante dui, laoreet ut rutrum ut, gravida vel orci. Ut tempus, est at feugiat posuere, nibh lectus euismod massa, non mattis arcu augue ut leo. Maecenas cursus fringilla elit. Fusce quis magna gravida, tempor ipsum mollis, tincidunt nunc. Nullam lacinia est sit amet felis efficitur, vel luctus turpis pellentesque. Maecenas nec placerat ligula. Maecenas sem nulla, sagittis non volutpat vel, elementum eget ipsum. Quisque tristique eleifend est, vitae semper neque condimentum eget. Nam ut aliquam diam, id viverra sapien. Vivamus aliquet id lorem vel efficitur. Sed euismod nisi quis leo dignissim convallis. Cras quis congue nibh. Sed ultrices nulla eu neque tincidunt commodo. Fusce pharetra arcu quis dictum eleifend.\r\n\r\nNam sit amet felis sed nibh semper eleifend accumsan et tellus. Nam pellentesque, nisi at consequat facilisis, lectus lacus euismod nulla, sit amet euismod quam odio nec felis. Fusce in massa eget ex vehicula tristique ac vitae neque. Maecenas a risus ut urna mollis dapibus sit amet vel ligula. Nulla interdum nibh non rhoncus eleifend. Donec vestibulum dui ut odio viverra, eu iaculis nunc sodales. Curabitur non ipsum vitae quam volutpat hendrerit. Donec urna nisl, tempor id molestie et, ullamcorper sed dolor. Morbi at viverra arcu. Maecenas mauris odio, tempus ac auctor ut, eleifend in lorem.\r\n\r\nAenean egestas bibendum feugiat. Nulla ornare venenatis consequat. Nam eu ligula convallis, sodales ex ac, finibus nulla. Mauris elementum nisi sed nibh laoreet cursus. Vivamus a diam at nisi feugiat porttitor. Morbi ultricies, nisl sit amet iaculis vehicula, sapien mi placerat ex, a fermentum risus justo ac eros. Maecenas ullamcorper aliquam porttitor. Vestibulum sagittis non purus eget euismod. Sed aliquet vestibulum risus, elementum feugiat diam rhoncus nec.\r\n\r\nIn eget arcu quis nibh tincidunt viverra sit amet sed nisi. Duis eu enim sed metus semper tempus vitae sit amet nisl. Suspendisse a sapien interdum, bibendum nunc id, volutpat nibh. Nam turpis quam, interdum sit amet aliquet quis, rutrum ac leo. Pellentesque aliquam gravida venenatis. Vestibulum consectetur sem ornare enim facilisis, a efficitur quam volutpat. Nulla vulputate mattis rutrum. Nulla commodo lacus quis nisi consequat, sit amet feugiat augue scelerisque. Sed mattis mauris lacus, ut mattis purus interdum eu. Maecenas bibendum magna vel lectus venenatis placerat. Maecenas quis nulla vitae massa placerat tincidunt. In sed suscipit eros. Sed commodo dignissim blandit. Nullam elit sem, iaculis eget aliquet a, ornare vel ipsum. Donec at aliquet velit.', 'img/noticia-1.jpg', '2018-08-24 17:23:00', 'manogray'),
(58, 'SpiderMan na nova geração!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ante dui, laoreet ut rutrum ut, gravida vel orci. Ut tempus, est at feugiat posuere, nibh lectus euismod massa, non mattis arcu augue ut leo. Maecenas cursus fringilla elit. Fusce quis magna gravida, tempor ipsum mollis, tincidunt nunc. Nullam lacinia est sit amet felis efficitur, vel luctus turpis pellentesque. Maecenas nec placerat ligula. Maecenas sem nulla, sagittis non volutpat vel, elementum eget ipsum. Quisque tristique eleifend est, vitae semper neque condimentum eget. Nam ut aliquam diam, id viverra sapien. Vivamus aliquet id lorem vel efficitur. Sed euismod nisi quis leo dignissim convallis. Cras quis congue nibh. Sed ultrices nulla eu neque tincidunt commodo. Fusce pharetra arcu quis dictum eleifend.\r\n\r\nNam sit amet felis sed nibh semper eleifend accumsan et tellus. Nam pellentesque, nisi at consequat facilisis, lectus lacus euismod nulla, sit amet euismod quam odio nec felis. Fusce in massa eget ex vehicula tristique ac vitae neque. Maecenas a risus ut urna mollis dapibus sit amet vel ligula. Nulla interdum nibh non rhoncus eleifend. Donec vestibulum dui ut odio viverra, eu iaculis nunc sodales. Curabitur non ipsum vitae quam volutpat hendrerit. Donec urna nisl, tempor id molestie et, ullamcorper sed dolor. Morbi at viverra arcu. Maecenas mauris odio, tempus ac auctor ut, eleifend in lorem.\r\n\r\nAenean egestas bibendum feugiat. Nulla ornare venenatis consequat. Nam eu ligula convallis, sodales ex ac, finibus nulla. Mauris elementum nisi sed nibh laoreet cursus. Vivamus a diam at nisi feugiat porttitor. Morbi ultricies, nisl sit amet iaculis vehicula, sapien mi placerat ex, a fermentum risus justo ac eros. Maecenas ullamcorper aliquam porttitor. Vestibulum sagittis non purus eget euismod. Sed aliquet vestibulum risus, elementum feugiat diam rhoncus nec.\r\n\r\nIn eget arcu quis nibh tincidunt viverra sit amet sed nisi. Duis eu enim sed metus semper tempus vitae sit amet nisl. Suspendisse a sapien interdum, bibendum nunc id, volutpat nibh. Nam turpis quam, interdum sit amet aliquet quis, rutrum ac leo. Pellentesque aliquam gravida venenatis. Vestibulum consectetur sem ornare enim facilisis, a efficitur quam volutpat. Nulla vulputate mattis rutrum. Nulla commodo lacus quis nisi consequat, sit amet feugiat augue scelerisque. Sed mattis mauris lacus, ut mattis purus interdum eu. Maecenas bibendum magna vel lectus venenatis placerat. Maecenas quis nulla vitae massa placerat tincidunt. In sed suscipit eros. Sed commodo dignissim blandit. Nullam elit sem, iaculis eget aliquet a, ornare vel ipsum. Donec at aliquet velit.', 'img/noticia-2.jpg', '2018-08-23 14:23:00', 'manogray'),
(59, 'James Gunn é recontratado!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ante dui, laoreet ut rutrum ut, gravida vel orci. Ut tempus, est at feugiat posuere, nibh lectus euismod massa, non mattis arcu augue ut leo. Maecenas cursus fringilla elit. Fusce quis magna gravida, tempor ipsum mollis, tincidunt nunc. Nullam lacinia est sit amet felis efficitur, vel luctus turpis pellentesque. Maecenas nec placerat ligula. Maecenas sem nulla, sagittis non volutpat vel, elementum eget ipsum. Quisque tristique eleifend est, vitae semper neque condimentum eget. Nam ut aliquam diam, id viverra sapien. Vivamus aliquet id lorem vel efficitur. Sed euismod nisi quis leo dignissim convallis. Cras quis congue nibh. Sed ultrices nulla eu neque tincidunt commodo. Fusce pharetra arcu quis dictum eleifend.\r\n\r\nNam sit amet felis sed nibh semper eleifend accumsan et tellus. Nam pellentesque, nisi at consequat facilisis, lectus lacus euismod nulla, sit amet euismod quam odio nec felis. Fusce in massa eget ex vehicula tristique ac vitae neque. Maecenas a risus ut urna mollis dapibus sit amet vel ligula. Nulla interdum nibh non rhoncus eleifend. Donec vestibulum dui ut odio viverra, eu iaculis nunc sodales. Curabitur non ipsum vitae quam volutpat hendrerit. Donec urna nisl, tempor id molestie et, ullamcorper sed dolor. Morbi at viverra arcu. Maecenas mauris odio, tempus ac auctor ut, eleifend in lorem.\r\n\r\nAenean egestas bibendum feugiat. Nulla ornare venenatis consequat. Nam eu ligula convallis, sodales ex ac, finibus nulla. Mauris elementum nisi sed nibh laoreet cursus. Vivamus a diam at nisi feugiat porttitor. Morbi ultricies, nisl sit amet iaculis vehicula, sapien mi placerat ex, a fermentum risus justo ac eros. Maecenas ullamcorper aliquam porttitor. Vestibulum sagittis non purus eget euismod. Sed aliquet vestibulum risus, elementum feugiat diam rhoncus nec.\r\n\r\nIn eget arcu quis nibh tincidunt viverra sit amet sed nisi. Duis eu enim sed metus semper tempus vitae sit amet nisl. Suspendisse a sapien interdum, bibendum nunc id, volutpat nibh. Nam turpis quam, interdum sit amet aliquet quis, rutrum ac leo. Pellentesque aliquam gravida venenatis. Vestibulum consectetur sem ornare enim facilisis, a efficitur quam volutpat. Nulla vulputate mattis rutrum. Nulla commodo lacus quis nisi consequat, sit amet feugiat augue scelerisque. Sed mattis mauris lacus, ut mattis purus interdum eu. Maecenas bibendum magna vel lectus venenatis placerat. Maecenas quis nulla vitae massa placerat tincidunt. In sed suscipit eros. Sed commodo dignissim blandit. Nullam elit sem, iaculis eget aliquet a, ornare vel ipsum. Donec at aliquet velit.', 'img/noticia-3.jpg', '2018-08-25 06:57:21', 'manogray'),
(60, 'Acordo entre DC Comics e Ubisoft!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ante dui, laoreet ut rutrum ut, gravida vel orci. Ut tempus, est at feugiat posuere, nibh lectus euismod massa, non mattis arcu augue ut leo. Maecenas cursus fringilla elit. Fusce quis magna gravida, tempor ipsum mollis, tincidunt nunc. Nullam lacinia est sit amet felis efficitur, vel luctus turpis pellentesque. Maecenas nec placerat ligula. Maecenas sem nulla, sagittis non volutpat vel, elementum eget ipsum. Quisque tristique eleifend est, vitae semper neque condimentum eget. Nam ut aliquam diam, id viverra sapien. Vivamus aliquet id lorem vel efficitur. Sed euismod nisi quis leo dignissim convallis. Cras quis congue nibh. Sed ultrices nulla eu neque tincidunt commodo. Fusce pharetra arcu quis dictum eleifend.\r\n\r\nNam sit amet felis sed nibh semper eleifend accumsan et tellus. Nam pellentesque, nisi at consequat facilisis, lectus lacus euismod nulla, sit amet euismod quam odio nec felis. Fusce in massa eget ex vehicula tristique ac vitae neque. Maecenas a risus ut urna mollis dapibus sit amet vel ligula. Nulla interdum nibh non rhoncus eleifend. Donec vestibulum dui ut odio viverra, eu iaculis nunc sodales. Curabitur non ipsum vitae quam volutpat hendrerit. Donec urna nisl, tempor id molestie et, ullamcorper sed dolor. Morbi at viverra arcu. Maecenas mauris odio, tempus ac auctor ut, eleifend in lorem.\r\n\r\nAenean egestas bibendum feugiat. Nulla ornare venenatis consequat. Nam eu ligula convallis, sodales ex ac, finibus nulla. Mauris elementum nisi sed nibh laoreet cursus. Vivamus a diam at nisi feugiat porttitor. Morbi ultricies, nisl sit amet iaculis vehicula, sapien mi placerat ex, a fermentum risus justo ac eros. Maecenas ullamcorper aliquam porttitor. Vestibulum sagittis non purus eget euismod. Sed aliquet vestibulum risus, elementum feugiat diam rhoncus nec.\r\n\r\nIn eget arcu quis nibh tincidunt viverra sit amet sed nisi. Duis eu enim sed metus semper tempus vitae sit amet nisl. Suspendisse a sapien interdum, bibendum nunc id, volutpat nibh. Nam turpis quam, interdum sit amet aliquet quis, rutrum ac leo. Pellentesque aliquam gravida venenatis. Vestibulum consectetur sem ornare enim facilisis, a efficitur quam volutpat. Nulla vulputate mattis rutrum. Nulla commodo lacus quis nisi consequat, sit amet feugiat augue scelerisque. Sed mattis mauris lacus, ut mattis purus interdum eu. Maecenas bibendum magna vel lectus venenatis placerat. Maecenas quis nulla vitae massa placerat tincidunt. In sed suscipit eros. Sed commodo dignissim blandit. Nullam elit sem, iaculis eget aliquet a, ornare vel ipsum. Donec at aliquet velit.', 'img/noticia-4.jpg', '2018-08-25 13:57:21', 'manogray'),
(72, 'Hugh Jackman não assina com a Disney!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer finibus finibus augue, ac ornare mauris. Sed id lacinia enim. Quisque cursus cursus purus, quis sodales nibh tempus non. Nullam in lacus ipsum. In sit amet tincidunt arcu, vel tristique sapien. Donec hendrerit et massa vel tincidunt. Donec gravida turpis ac nulla ultricies, ut mattis purus varius. Fusce pulvinar dapibus velit vitae dictum.\r\n\r\nIn hac habitasse platea dictumst. Phasellus imperdiet dignissim malesuada. Aliquam eget ligula id nisl scelerisque faucibus. Nam accumsan eget orci eget lacinia. Etiam porttitor velit at semper aliquet. Praesent malesuada facilisis justo, vestibulum lacinia sapien consectetur ut. Phasellus quis arcu vitae quam aliquet pulvinar. Mauris dictum, ante a placerat sagittis, ex purus pretium est, a aliquet ligula turpis bibendum turpis. Nunc eget ipsum quis orci sollicitudin aliquet ut vitae lacus. Cras risus ligula, elementum eget velit id, consequat fringilla ante. Aenean ut blandit massa. Suspendisse cursus massa non lectus auctor, sit amet faucibus metus lobortis. Duis fermentum ligula in dui accumsan rhoncus. Vestibulum ligula justo, congue in dictum ut, suscipit ut erat. Donec tortor magna, consequat vitae cursus in, sollicitudin faucibus magna. In eu condimentum risus.\r\n\r\nNullam sit amet elit quis nibh faucibus lobortis. Etiam rhoncus tellus sit amet est auctor, tincidunt tincidunt ex maximus. Vestibulum ac ornare arcu, at bibendum nunc. Morbi in risus eget velit accumsan eleifend. Ut rhoncus aliquet nunc, vitae porttitor enim vestibulum id. Pellentesque magna nisi, tempor at lectus sit amet, dictum semper augue. Mauris commodo, risus et porta viverra, nibh turpis facilisis magna, vel egestas erat elit vel magna. Vivamus id neque est. Quisque rutrum, erat sit amet cursus gravida, sem leo convallis orci, a facilisis felis lacus molestie quam. Nulla aliquam aliquet aliquam. Aliquam ut porta ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi id augue id turpis ultrices auctor. Pellentesque convallis a turpis ut auctor. Duis efficitur sem quis quam ultricies facilisis. Morbi finibus vel dolor nec vestibulum.', 'img/63-valkirias-logan-5.png', '2018-08-27 03:35:15', 'manogray'),
(73, 'Novo filme do homem formiga', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer finibus finibus augue, ac ornare mauris. Sed id lacinia enim. Quisque cursus cursus purus, quis sodales nibh tempus non. Nullam in lacus ipsum. In sit amet tincidunt arcu, vel tristique sapien. Donec hendrerit et massa vel tincidunt. Donec gravida turpis ac nulla ultricies, ut mattis purus varius. Fusce pulvinar dapibus velit vitae dictum.\r\n\r\nIn hac habitasse platea dictumst. Phasellus imperdiet dignissim malesuada. Aliquam eget ligula id nisl scelerisque faucibus. Nam accumsan eget orci eget lacinia. Etiam porttitor velit at semper aliquet. Praesent malesuada facilisis justo, vestibulum lacinia sapien consectetur ut. Phasellus quis arcu vitae quam aliquet pulvinar. Mauris dictum, ante a placerat sagittis, ex purus pretium est, a aliquet ligula turpis bibendum turpis. Nunc eget ipsum quis orci sollicitudin aliquet ut vitae lacus. Cras risus ligula, elementum eget velit id, consequat fringilla ante. Aenean ut blandit massa. Suspendisse cursus massa non lectus auctor, sit amet faucibus metus lobortis. Duis fermentum ligula in dui accumsan rhoncus. Vestibulum ligula justo, congue in dictum ut, suscipit ut erat. Donec tortor magna, consequat vitae cursus in, sollicitudin faucibus magna. In eu condimentum risus.\r\n\r\nNullam sit amet elit quis nibh faucibus lobortis. Etiam rhoncus tellus sit amet est auctor, tincidunt tincidunt ex maximus. Vestibulum ac ornare arcu, at bibendum nunc. Morbi in risus eget velit accumsan eleifend. Ut rhoncus aliquet nunc, vitae porttitor enim vestibulum id. Pellentesque magna nisi, tempor at lectus sit amet, dictum semper augue. Mauris commodo, risus et porta viverra, nibh turpis facilisis magna, vel egestas erat elit vel magna. Vivamus id neque est. Quisque rutrum, erat sit amet cursus gravida, sem leo convallis orci, a facilisis felis lacus molestie quam. Nulla aliquam aliquet aliquam. Aliquam ut porta ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi id augue id turpis ultrices auctor. Pellentesque convallis a turpis ut auctor. Duis efficitur sem quis quam ultricies facilisis. Morbi finibus vel dolor nec vestibulum.', 'img/64-painel-para-festa-infantil-homem-formiga-painel-de-aniversario.jpg', '2018-08-27 04:55:17', 'manogray'),
(74, 'Deadpool 2 foi anunciado!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer finibus finibus augue, ac ornare mauris. Sed id lacinia enim. Quisque cursus cursus purus, quis sodales nibh tempus non. Nullam in lacus ipsum. In sit amet tincidunt arcu, vel tristique sapien. Donec hendrerit et massa vel tincidunt. Donec gravida turpis ac nulla ultricies, ut mattis purus varius. Fusce pulvinar dapibus velit vitae dictum.\r\n\r\nIn hac habitasse platea dictumst. Phasellus imperdiet dignissim malesuada. Aliquam eget ligula id nisl scelerisque faucibus. Nam accumsan eget orci eget lacinia. Etiam porttitor velit at semper aliquet. Praesent malesuada facilisis justo, vestibulum lacinia sapien consectetur ut. Phasellus quis arcu vitae quam aliquet pulvinar. Mauris dictum, ante a placerat sagittis, ex purus pretium est, a aliquet ligula turpis bibendum turpis. Nunc eget ipsum quis orci sollicitudin aliquet ut vitae lacus. Cras risus ligula, elementum eget velit id, consequat fringilla ante. Aenean ut blandit massa. Suspendisse cursus massa non lectus auctor, sit amet faucibus metus lobortis. Duis fermentum ligula in dui accumsan rhoncus. Vestibulum ligula justo, congue in dictum ut, suscipit ut erat. Donec tortor magna, consequat vitae cursus in, sollicitudin faucibus magna. In eu condimentum risus.', 'img/62-batman.jpg', '2018-08-26 17:38:01', 'manogray'),
(76, 'Novo filme guardiões da galáxia: Origem', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/76-guardioes-da-galaxia-1.jpg', '2018-08-27 19:26:55', 'strike'),
(77, 'Filme solo de Os Supremos', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/77-supremos.jpg', '2018-08-27 19:28:27', 'strike'),
(78, 'Filmoteca exibe mostra especial da DC Comics durante toda semana em Rio Branco', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/78-wwsw.jpg', '2018-08-27 19:31:37', 'strike'),
(79, 'Hasbro e DC Comics resolvem disputa judicial sobre Bumblebee', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/79-Bumblebee-1068x601.jpg', '2018-08-27 19:33:57', 'strike'),
(80, 'Vingadores 4 | X-Men se unem aos heróis da Marvel em trailer criado por fã', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/80-vingadoresxmen-1068x534.jpg', '2018-08-27 19:36:02', 'strike'),
(81, 'Conheça algumas participações inusitadas de personagens no universo Marvel', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/81-chuck.jpg', '2018-08-27 19:37:34', 'strike'),
(82, 'Fãs descobrem que Pepper Potts matou mais personagens na Marvel do que o Homem de Ferro', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/82-1-pepper.jpg', '2018-08-27 19:39:41', 'strike'),
(83, 'Capitã Marvel | Confira novas artes promocionais do filme', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/83-Capita-Marvel-Capa.jpg', '2018-08-27 19:41:02', 'strike'),
(84, 'Serviço de streaming da DC Comics vai ter programa diário de informações', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/84-339907.jpg', '2018-08-27 19:42:41', 'manogray'),
(85, 'Deadpool 2: Site ensina como se candidatar para a X-Force', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/85-DkvfosxV4AA6j4t.jpg', '2018-08-27 19:45:02', 'manogray'),
(86, 'Deadpool 2: Diretor explica como Celine Dion substituiu Adele na trilha do filme', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/86-Deadpool-2.jpg', '2018-08-27 19:48:17', 'manogray'),
(87, 'X-Force | Ryan Reynolds quer Hugh Jackman no filme, mas não como Wolverine', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/87-1-hj.jpg', '2018-08-27 19:52:17', 'manogray'),
(88, 'Garras de Wolverine estão fervendo em estreia de nova HQ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet imperdiet ante. Duis pulvinar vitae felis eu semper. Aliquam ex turpis, condimentum ut elementum vitae, vulputate vitae tortor. Vestibulum vel quam diam. Integer sollicitudin bibendum lorem, et egestas sem consequat nec. Aenean venenatis lectus a dolor gravida fringilla. Integer at rutrum nisl, ut ullamcorper quam.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas augue nec imperdiet auctor. Ut at magna molestie urna commodo sagittis a non dui. Quisque et consectetur purus. Duis rhoncus mauris lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consectetur ante ultricies, vestibulum ante non, tincidunt nunc. Ut et semper velit. Aliquam vestibulum ut libero vitae vestibulum. Donec fermentum velit id sem blandit, eget malesuada nibh egestas. Vestibulum varius, ante eu vehicula volutpat, nibh libero ullamcorper urna, venenatis viverra magna nibh in ipsum. Ut magna neque, tristique a ex in, semper fringilla nisi. Nunc in ante maximus, rhoncus ex porta, gravida augue. Ut blandit tempor gravida. Pellentesque tempus, massa eget luctus vestibulum, ex diam dignissim risus, eu finibus purus risus quis mauris. Praesent non sem eleifend, sodales neque vitae, luctus turpis.', 'img/88-wolverine-return-of-wolverine.jpg', '2018-08-27 19:53:02', 'manogray');

-- --------------------------------------------------------

--
-- Estrutura da tabela `usuario`
--

CREATE TABLE `usuario` (
  `ID` int(11) NOT NULL,
  `nickname` varchar(100) CHARACTER SET latin1 NOT NULL,
  `email` varchar(100) CHARACTER SET latin1 NOT NULL,
  `senha` varchar(100) CHARACTER SET latin1 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `usuario`
--

INSERT INTO `usuario` (`ID`, `nickname`, `email`, `senha`) VALUES
(1, 'manogray', 'lgmpf@icomp.ufam.edu.br', '745701cfafd7e0944c807accf4371fba'),
(4, 'strike', 'strike@gmail.com', '7c2e6a95f4a6b8f0573f0fdc26da4c9b');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `noticia`
--
ALTER TABLE `noticia`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `usuario`
--
ALTER TABLE `usuario`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `noticia`
--
ALTER TABLE `noticia`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=89;

--
-- AUTO_INCREMENT for table `usuario`
--
ALTER TABLE `usuario`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
